### ISSUE TITLE
validation error when value is zero for integer

### ISSUE THREAD

**Issue by whmbuaa** [ppoffice/validator.js#1]
rules = {
     a : "required|integer"
}

obj = {
   a: 0
}

will error

**Comment by ppoffice** [comment]
@whmbuaa 
Please update the dependency and see if this issue is solved.

Also, I am very sorry to inform you that I will no longer maintenance this project. But you can find many similar projects on [Npm.js](https://www.npmjs.com/search?q=laravel%20validation&page=1&ranking=popularity). Thank you for your support.
